### ISSUE TITLE
No dependencies detected

### ISSUE THREAD

**Issue by wouterdb** [librariesio/pydeps#4]
## Bugs
- [ ] the inmanta project has no dependencies reported on https://libraries.io/pypi/inmanta while many dependencies are both in the [requirements.txt](https://github.com/inmanta/inmanta/blob/master/requirements.txt) and the [setup.py](https://github.com/inmanta/inmanta/blob/master/setup.py)

**Comment by mikeyoung85** [comment]
Updated the `pydeps` container to use Python 3.6 to help resolve dependencies. Looks like it is able to pull in dependencies for version `2019.2.1` for `inmanta` now. https://libraries.io/pypi/inmanta shows 16 dependencies.
